# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306e47c79cfa0c44524ecbf3f5258fdea0dcd350eeeadee7176676e7094e0459bbf12c4452bc15ee0ae2218bf13e22a9e937dce4c54d291a0dc701819e5d8033

test:
  secret_key_base: a32d3f24e19f760798bc69b31c5c1fa8d73323f0f596fbca6819c49d614effe2780b7c62a58bdd9da9c39fed44832397fd40865b5700774d824c1835152f8e6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
